### PR TITLE
german acp.php

### PR DESCRIPTION
**Pull request by jan-2017**
Translation in to German
Folder "de" created

### CODE REVIEW

**Comment by marttiphpbb** [comment]
Ok, thanks!

**Comment by jan-2017** [comment]
thanks for your helpful guide
and....thanks for extension ;)

marttiphpbb <notifications@github.com> schrieb am Sa., 21. Apr. 2018, 08:41:

**Comment by marttiphpbb** [comment]
The file was wrongly in the root, not in the language/de folder. But no problem, I've moved it.

**Comment by jan-2017** [comment]
oh sorry ... thanks.

Now I understand it. First select the directory in which I want to make a
change and then click on Fork.

marttiphpbb <notifications@github.com> schrieb am Sa., 21. Apr. 2018, 08:47:

**Pull request merged**
